### ISSUE TITLE
Support for Graylog 4

### ISSUE THREAD

**Issue by svenwltr** [graylog-labs/graylog-plugin-pagerduty#22]
When installing on a Graylog 4.0.1 server it seems to properly load the plugin:

```
2021-01-07 15:31:24,683 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: PagerDutyNotificationPlugin 2.0.0 [org.graylog.plugins.pagerduty.PagerDutyNotificationPluginPlugin]
```

However there is no Pager Duty notification option:

![image](https://user-images.githubusercontent.com/1698599/103914195-bea56d00-5109-11eb-94a9-b65064dcad9a.png)

I assume there is no Graylog 4 support yet, since I do not see any error in the Graylog logs.

**Comment by bernd** [comment]
@svenwltr The `graylog-plugin-integrations-plugins` package [includes the PagerDuty plugin since 4.0](https://docs.graylog.org/en/4.0/pages/changelog.html#id3). So there is no need to install this plugin separately anymore. See the [integrations plugin installation instructions](https://docs.graylog.org/en/4.0/pages/integrations/setup.html) for more details.

I hope that helps.

**Comment by svenwltr** [comment]
Thanks @bernd, that worked. The install instructions were a bit confusing, because the listed versions still were for versions 3.x. I replaced the download URLs with `4.0.0` and it worked.
